image: python:3.7-stretch

before_script:
    - python -V
    - pip install pylint
    - git clone https://github.com/Rapptz/discord.py.git
    - pip install discord.py/
    
stages:
    - test


lint:
    stage: test
    script:
        - bash pylinter-error-check