image: python:3.7-stretch

before_script:
    - python -V
    - pip install pylint
    - git clone https://github.com/Rapptz/discord.py.git
    - pip install discord.py/
    
stages:
    - test
    - deploy


lint:
    stage: test
    script:
        - bash pylinter-error-check

deploy:
    stage: deploy
    script:
        - mkdir /root/.ssh/
        - cp privatekey ~/.ssh/id_rsa
        - cp sshkey ~/.ssh/id_rsa.pub
        - git remote remove dokku || exit 0
        - git remote add dokku dokku@videojeux4.ga:rphelper
        - git push dokku master