image: python:3.7-stretch

before_script:
    - python -V
    - pip install pylint
    - git clone https://github.com/Rapptz/discord.py.git
    - pip install discord.py/
    
stages:
    - test
    - deploy


lint:
    stage: test
    script:
        - bash pylinter-error-check

deploy:
    stage: deploy
    script:
        - mkdir ~/.ssh/
        - chmod 700 ~/.ssh
        - echo "$PRIVATE_SSH" > ~/.ssh/id_rsa
        - chmod 644 ~/.ssh/id_rsa
        - cp sshkey ~/.ssh/id_rsa.pub
        - chmod 644 ~/.ssh/id_rsa.pub
        - git remote add dokku dokku@videojeux4.ga:rphelper
        - git push dokku master